name: thisisnabi.dev

env:
  DOTNET_VERSION: '8'
  
on:
  push:
    branches: [ "main" ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: Set up .NET 
      uses: actions/setup-dotnet@v3
      with: 
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore Nuget packages
      run: dotnet restore

    - name: Build Project
      run: dotnet build --no-restore

    - name: Liara-Publish
      env:
        LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
      run: |
        npm i -g @liara/cli@5
        liara deploy --app="APP_NAME" --api-token="$LIARA_TOKEN" --no-app-logs
